from flask import Blueprint, request, jsonify
from werkzeug.utils import secure_filename
import os

cover_letter_bp = Blueprint('cover_letter', __name__)

# PUBLIC_INTERFACE
@cover_letter_bp.route('/cover-letter', methods=['POST'])
def generate_cover_letter():
    """
    ---
    summary: Generate a customized cover letter (AI-powered, mocked)
    description: |
      Accepts job role, job description, resume file (or text), and tone.
      Returns a customized cover letter generated by AI (mock implementation).
    tags:
      - Cover Letter
    consumes:
      - multipart/form-data
    parameters:
      - in: formData
        name: job_role
        type: string
        required: true
        description: Target job role/position
      - in: formData
        name: job_description
        type: string
        required: true
        description: The job description text
      - in: formData
        name: resume
        type: file
        required: false
        description: Resume file (PDF/DOCX)
      - in: formData
        name: resume_text
        type: string
        required: false
        description: Resume text content (as alternative to file)
      - in: formData
        name: tone
        type: string
        required: true
        description: Desired tone of cover letter
    responses:
      200:
        description: Success with generated cover letter
        schema:
          type: object
          properties:
            cover_letter:
              type: string
              description: AI-generated cover letter
      400:
        description: Invalid input
    """
    # Parse form data
    job_role = request.form.get('job_role', '').strip()
    job_description = request.form.get('job_description', '').strip()
    tone = request.form.get('tone', 'professional').strip().lower()
    resume_file = request.files.get('resume')
    resume_text = request.form.get('resume_text', '').strip()

    if not job_role or not job_description or not tone:
        return jsonify({"detail": "Missing required fields."}), 400
    if (not resume_file and not resume_text) or (resume_file and resume_text):
        return jsonify({"detail": "Provide either a resume file or resume text, not both."}), 400

    # For now, just read limited text as a mock (not real AI call)
    if resume_text:
        resume_content = resume_text[:500]
    elif resume_file:
        filename = secure_filename(resume_file.filename)
        # Read file content, in a real impl would parse/extract from PDF/DOCX
        resume_content = resume_file.read(1024).decode(errors="ignore")[:500]
    else:
        resume_content = ""

    # Mock AI output
    cover_letter = f"""Dear Hiring Manager,

I am writing to express my strong interest in the position of {job_role}. My background and qualifications, as outlined in my resume, closely align with the requirements described for this role.

({ "Tone: " + tone.capitalize() }) 

Job Description Snapshot:
{job_description[:300]}...

Resume Highlights:
{resume_content if resume_content else "[Resume provided as file]"}...

Thank you for considering my application. I am excited about the opportunity to contribute and look forward to discussing my fit for this role.

Sincerely,
[Your Name]"""

    return jsonify({"cover_letter": cover_letter})
