from flask import Blueprint, request, jsonify
from jobtrack_ai_backend.app.services.cohere_client import CohereClient

cover_letter_bp = Blueprint('cover_letter', __name__)


# PUBLIC_INTERFACE
@cover_letter_bp.route('/cover-letter', methods=['POST'])
def generate_cover_letter():
    """
    ---
    summary: Generate a customized cover letter (AI-powered)
    description: |
      Accepts job role, job description, resume file (or text), and tone.
      Returns a customized cover letter generated by Cohere LLM (real implementation).
    tags:
      - Cover Letter
    consumes:
      - multipart/form-data
    parameters:
      - in: formData
        name: job_role
        type: string
        required: true
        description: Target job role/position
      - in: formData
        name: job_description
        type: string
        required: true
        description: The job description text
      - in: formData
        name: resume
        type: file
        required: false
        description: Resume file (PDF/DOCX)
      - in: formData
        name: resume_text
        type: string
        required: false
        description: Resume text content (as alternative to file)
      - in: formData
        name: tone
        type: string
        required: true
        description: Desired tone of cover letter
    responses:
      200:
        description: Success with generated cover letter
        schema:
          type: object
          properties:
            cover_letter:
              type: string
              description: AI-generated cover letter
      400:
        description: Invalid input
    """
    # Parse form data
    job_role = request.form.get('job_role', '').strip()
    job_description = request.form.get('job_description', '').strip()
    tone = request.form.get('tone', 'professional').strip().lower()
    resume_file = request.files.get('resume')
    resume_text = request.form.get('resume_text', '').strip()

    if not job_role or not job_description or not tone:
        return jsonify({"detail": "Missing required fields."}), 400
    if (not resume_file and not resume_text) or (resume_file and resume_text):
        return jsonify({"detail": "Provide either a resume file or resume text, not both."}), 400

    # Read resume content from text or file
    if resume_text:
        resume_content = resume_text[:2000]
    elif resume_file:
        try:
            resume_content = resume_file.read(4096).decode("utf-8", errors="ignore")
        except Exception:
            resume_content = ""
    else:
        resume_content = ""

    # Call Cohere to generate a real cover letter
    try:
        cohere = CohereClient()
        result = cohere.generate_cover_letter(
            job_role=job_role,
            job_description=job_description,
            resume_text=resume_content,
            tone=tone if tone else "professional"
        )
        return jsonify(result)
    except Exception as e:
        return jsonify({"detail": f"Cover letter generation failed: {str(e)}"}), 500
